### ISSUE TITLE
Figure out why FlowRunnerTest and FlowUtilsTest are broken with upgrade to cascading 3.1.0

### ISSUE THREAD

**Issue by vmagotra** [ScaleUnlimited/cascading.utils#23] opened 2015-11-24 20:50 UTC
After the upgrade to cascading 3.1.0 (wip-40), the tests in FlowRunnerTest and FlowUtilsTest don't pass.
The changes made to FlowRunner need to be verified.

**Comment by vmagotra** [comment] 2015-11-25 13:20
I've fixed the issue with FlowUtilsTest - in previous Cascading versions, LocalStepGraph#makeStepGraph set the name to "local" by default. This behavior isn't there in the 3.1 version of Cascading so the unit test has been updated.

**Comment by vmagotra** [comment] 2015-11-25 14:57
Now, the only test failing is testStatsHadoopMiniCluster() in FlowRunnerTest.
I wonder if https://issues.apache.org/jira/browse/YARN-2839 and https://issues.apache.org/jira/browse/YARN-90 are related to this issue.
When I run locally I see the following line : 
ERROR nodemanager.LocalDirsHandlerService:332 - Most of the disks failed. 4/4 local-dirs are bad:

**Comment by kkrugler** [comment] 2015-11-30 14:41
What I see is that the logs have the expected msgs, except that it's only running with one reduce task instead of two. So you get:

20151129 01:30:14       0       1       testStatsHadoopMiniCluster|group on total (2/2) ...tsHadoopMiniCluster/out-0=0,1; 

where it's expected to have "<tab>0<tab>2<tab> after the timestamp.

I think the issue is that we need to set up the mini-cluster with appropriate capacity (e.g. 3 containers) via the various YARN properties (there's a TODO in the MiniClusterPlatform.setupMiniClusterPlatform() method about exactly that).

I'll see if I can figure out the right combination of settings - attempt #1 didn't work.

**Comment by kkrugler** [comment] 2015-11-30 15:45
Making progress - there's new support for a YARN-based mini-cluster, but still haven't figured out why the ResourceManager isn't allocating two containers during the reduce phase. It might be that by the time the second reduce task is being fired up, the first task is already done, so you never have both running at the same time.

**Comment by kkrugler** [comment] 2016-03-29 00:08
I've opened issue #26 to address the remaining known problem, so I'll close this now.

**Closed by kkrugler** 2016-03-29 00:08 UTC
